name: $(ReleaseVersionNumber) Build $(Build)
variables:
  ReleaseVersionNumber: 2.0.0
  Build: $[counter(variables['ReleaseVersionNumber'], 1)]
  PrereleaseVersionNumber: $(ReleaseVersionNumber)-beta$(Build)
  AssemblyVersion: $(ReleaseVersionNumber).$(Build)
  InformationalVersion: $(ReleaseVersionNumber) build $(Build)

trigger:
  paths:
    include:
      - src
    
jobs:
  - job:
    displayName: 'Build, test, pacakge'
    pool:
      vmImage: windows-latest
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore packages
        inputs:
          command: restore
          configuration: release
          projects: |
            **/*.csproj

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          arguments: --no-restore -c release -p:Version=$(AssemblyVersion) -p:"InformationalVersion=$(InformationalVersion)"
          projects: |
            src/**/*.csproj
            
      - task: DotNetCoreCLI@2
        displayName: Pack for unstable
        inputs:
          command: custom
          custom: pack
          arguments: --no-build -c release -p:PackageVersion=$(PrereleaseVersionNumber) -o $(Build.ArtifactStagingDirectory)/cicd
          projects: |
            src/**/*.csproj

      - task: DotNetCoreCLI@2
        displayName: Pack for stable
        inputs:
          command: custom
          custom: pack
          arguments: --no-build -c release -p:PackageVersion=$(ReleaseVersionNumber) -o $(Build.ArtifactStagingDirectory)/dist
          projects: |
            src/**/*.csproj

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
